networks:
  local_network:

services:
  api_tests: 
    container_name: ktax-it-api-test
    build: 
      context: . 
      dockerfile: ./Dockerfile.test 
    volumes: 
      - .:/go/src/target 
    environment:
      API_URL: http://ktax-it-api:8080
    depends_on: 
      - api 
    networks: 
      - local_network
  api: 
    container_name: ktax-it-api
    build: 
      context: . 
      dockerfile: Dockerfile 
    environment:
      PORT: 8080
      DATABASE_URL: host=ktax-it-db port=5432 user=postgres password=postgres dbname=ktaxes sslmode=disable
      ADMIN_USERNAME: adminTax
      ADMIN_PASSWORD: admin!
    ports: 
      - "8080:8080" 
    volumes: 
      - .:/app 
    depends_on: 
      db: 
        condition: service_healthy 
    networks: 
      - local_network
  db: 
    container_name: ktax-it-db
    image: postgres:16 
    environment: 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: ktaxes 
    volumes: 
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql 
    ports: 
      - '5432:5432' 
    networks: 
      - local_network
    restart: on-failure 
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready"]